const constants = {
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",
    SORT_COLORS: "SORT_COLORS",
    EDIT_COLOR: "EDIT_COLOR",
    EDIT_SELECTED: "EDIT_SELECTED",

    LOAD_BOOKS: "LOAD_BOOKS",
    ADD_BOOK: "ADD_BOOK",
    REMOVE_BOOK: "REMOVE_BOOK",
    SORT_BOOKS: "SORT_BOOKS",
    EDIT_BOOK: "EDIT_BOOK",
    EDIT_SELECTED_BOOK: "EDIT_SELECTED_BOOK",

    SET_CURFORM: "SET_CURFORM",
    SET_IS_INS: "SET_IS_INS",

    LOAD_WEATHER: "LOAD_WEATHER"

}

export default constants